Revert "Second version of mdx-to-hast transformer"
gravitational/docs pull request #241
Opened 2023-02-28 19:18 UTC by alexfornuto

Reverts gravitational/docs#225

2023-02-28 19:53 UTC, ptgott approved these changes

2023-02-28 20:07 UTC, hatched requested changes
Instead of reverting all of these changes I've created a PR that appears to fix the root issue: https://github.com/gravitational/docs/pull/242

2023-03-06 18:26 UTC, alexfornuto commented
Re-opened to be re-evaluated, as several other bugs have been discovered and traced back to this change.

2023-03-06 19:32 UTC, hatched submitted a review, later dismissed

2023-03-07 21:36 UTC, hatched approved these changes

2023-03-07 21:56 UTC, merged