Third attempt at migrating to rehype
gravitational/docs pull request #253
Opened 2023-03-15 13:29 UTC by iAdramelk

Changes:

- #248 - fixes bugs with missing attributes and adds tests for the plugin.
- #243 - Make current version URLs with `/ver/x.x`work, but do not add them to the source map, and do not add them to the Algolia index. Both pages have the same canonical urls in the head (version without `/ver/x.x`).
- #247 is partially fixed – no need to reload the server anymore, but you still need to reload the pages. Making real hot reload work with `getServerSideProps` may be impossible or pretty hard.
- #161 - fixes image aspect ratio by updating to Next@13. Next@13 reworked the way images are inserted into the page by removing span wrappers and absolute positioning. It fixed a lot of problems with image proportions. To make it even more stable, I replaced `probe-image-size` library with the `image-size` library used by Next.js itself.
- Fix a minor bug with `Var` component hydration problem.

#246 is not a part of this PR because it is not related to rehype migration, I will work on it separately.

2023-03-16 14:26 UTC, iAdramelk commented on server/paths.ts
> +  const slug = path.split("/").filter((part) => part);
The original `slug` looks like this `/var/13.x/page-name/`, so we need to filter the first and the last blank segments. We could do it in the slug generation function, but then we will need to add them back to the source map and other places.

2023-03-16 14:28 UTC, iAdramelk commented on server/paths.ts
> +    }
Yes, right now, we push twice, but I am thinking about changing it to rewrites in config instead of actual paths.

2023-03-16 14:30 UTC, iAdramelk commented on server/paths.ts
> +    }
No, it sets values twice. E. g. `/docs/` and `/docs/ver/12.x/`. But I will also try  the redirect idea so w may not need it.

2023-03-16 15:51 UTC, iAdramelk commented
@avatus  Returned `older-versions` page and replaced the current version solution with redirects. Please check

2023-03-16 16:13 UTC, iAdramelk commented
@avatus ok, we have a problem, lol. I remember why I removed `older-versions` – we already have it in the docs, so we now have a naming conflict. Will add an exception for now, but we should remove `older-versions.mdx` from docs.

2023-03-16 16:44 UTC, avatus commented on server/paths.ts
> +        .filter((path) => path !== "/older-versions/") // We should remove older-versions.mdx from docs
We can remove this check once https://github.com/gravitational/teleport/pull/23192 gets pulled in. But good to know we have a killswitch for anything similar in the future. thank you!

2023-03-16 16:48 UTC, avatus approved these changes
Looks good to me and has been working great locally. Would wait for @alexfornuto to go over it as his comb is much more fine than mine

2023-03-16 18:48 UTC, alexfornuto requested changes
The Good
- Local refresh - working manually, though it's a bummer that live refresh won't work.
- Video auto playing - confirmed. 
- Images - reviewed several png and svg files, they all appear to render correctly.

The bad
- Versioned paths - Using a versioned link for the current version successfully redirects, but using the version switcher on the page errors out:

  ```
  error - ./content/11.x/docs/pages/deploy-a-cluster/introduction.mdx
  Module parse failed: Assigning to rvalue (1:2)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  > ---
  | title: "Running a Production Teleport Cluster"
  | description: "Guides to running Teleport in production."
  ```

  This error can't be escaped by navigating to another page, the dev server needs to be restarted.

- Vars - now that #254 is merged, can you rebase this branch against master to confirm that it all works when put together?

2023-03-16 18:57 UTC, iAdramelk commented
> error - ./content/11.x/docs/pages/deploy-a-cluster/introduction.mdx
> Module parse failed: Assigning to rvalue (1:2)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > ---
> | title: "Running a Production Teleport Cluster"
> | description: "Guides to running Teleport in production."

@alexfornuto Can please you check if you have `ver` folder with the mdx files inside the `pages` folder? If yes, can you remove them and try again? They are automatically placed in the folder by the previous build system and can break the new one.

2023-03-16 19:02 UTC, iAdramelk commented
BTW, rebased from the main and tested. It works.

2023-03-16 19:08 UTC, alexfornuto approved these changes
> Can please you check if you have `ver` folder with the mdx files inside the `pages` folder? If yes, can you remove them and try again?

👍 

Also tested and confirmed that vars are working. I think this is good, but would like to wait for @ptgott's review as well.

2023-03-17 17:03 UTC, ptgott commented
The only issue I've run into: when running `yarn dev`, editing a file, and writing the edits, the page doesn't refresh. I can still show the changes by refreshing manually. @alexfornuto Do you get the same issue and is that okay for you?

Otherwise, I've given the docs a quick browse with the dev server running and everything seems okay!

2023-03-17 19:51 UTC, avatus approved these changes

2023-03-19 18:47 UTC, iAdramelk commented
Ready to merge if @alexfornuto is ok with it.

2023-03-20 14:05 UTC, alexfornuto commented
@iAdramelk I am begrudgingly OK with it.

2023-03-20 14:08 UTC, merged