Add workflow to run the Mintlify migration
gravitational/docs pull request #441
Opened 2024-03-08 15:49 UTC by ptgott

The workflow runs the migration script and pushes to the `mintlify`
branch. It assumes that there is a GitHub app with its ID stored in
`vars` and private key in a secret, and that only this GitHub app has
permissions to push to the `mintlify` branch.

2024-03-08 15:50 UTC, ptgott commented
This PR is based on https://github.com/gravitational/docs/pull/437

2024-03-09 00:52 UTC, wadells commented on .github/workflows/mintlify.yml
> +          yarn mintlify
We're currently doing all this on the mintlify branch, as it was checked out immediately above. I think we want to pull in changes from `main` first, then rebuild.

2024-03-09 00:52 UTC, wadells commented on migration/base/favicon.png
Is this intended to be committed? I don't think we want it in `main`.

2024-03-11 15:07 UTC, ptgott commented on migration/base/favicon.png
👍 I'm not able to change my base branch to the fork, so I'll wait until we merge that PR (which should be soon) and rebase this one to `main`.

2024-03-21 16:59 UTC, wadells requested changes
Sasha has requested we put this on hold pending discussion around https://mintlify.com/blog/incident-march-13

I won't configure the app/secret needed for minlify to read the docs repo until that discussion is complete.

2024-04-15 13:48 UTC, closed without merging